import { AspectRatio, ImageResolution, StickerStyle, ModelType } from './types';
import { Palette, Zap, Star, Monitor, Ghost, PenTool } from 'lucide-react';

export const STICKER_STYLES: StickerStyle[] = [
  {
    id: 'classic-cartoon',
    name: 'Classic Cartoon',
    label_zh: '经典卡通',
    promptModifier: 'vibrant flat cartoon sticker, thick bold black outlines, simple shading, vector art style, cute and expressive',
    previewColor: 'bg-yellow-400',
    previewImage: '/style-previews/classic-cartoon.jpg',
  },
  {
    id: 'kawaii-chibi',
    name: 'Kawaii Chibi',
    label_zh: '可爱Q版',
    promptModifier: 'adorable kawaii chibi sticker, pastel colors, giant sparkling eyes, soft rounded shapes, bubbly aesthetic, white outline',
    previewColor: 'bg-pink-400',
    previewImage: '/style-previews/kawaii-chibi.jpg',
  },
  {
    id: '3d-glossy',
    name: '3D Glossy',
    label_zh: '3D光泽',
    promptModifier: '3D rendered toy sticker, plastic glossy texture, claymation style, soft studio lighting, cute character design, volumetric',
    previewColor: 'bg-blue-400',
    previewImage: '/style-previews/3d-glossy.jpg',
  },
  {
    id: 'vintage-badge',
    name: 'Vintage Badge',
    label_zh: '复古徽章',
    promptModifier: 'retro vintage sticker, muted color palette, textured paper feel, 70s badge style, distressed look, typography elements',
    previewColor: 'bg-orange-400',
    previewImage: '/style-previews/vintage-badge.jpg',
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art',
    label_zh: '像素艺术',
    promptModifier: 'pixel art sticker, 8-bit retro game style, blocky details, limited color palette, clean edges, white outline',
    previewColor: 'bg-purple-400',
    previewImage: '/style-previews/pixel-art.jpg',
  },
  {
    id: 'watercolor',
    name: 'Watercolor',
    label_zh: '水彩画',
    promptModifier: 'watercolor painted sticker, artistic brush strokes, soft gradients, paper texture, dreamy and whimsical, hand-painted look',
    previewColor: 'bg-teal-400',
    previewImage: '/style-previews/watercolor.jpg',
  },
  {
    id: 'neon-cyberpunk',
    name: 'Neon Cyberpunk',
    label_zh: '霓虹赛博',
    promptModifier: 'neon cyberpunk sticker, glowing lights, futuristic, dark background, synthwave colors, high contrast',
    previewColor: 'bg-fuchsia-600',
    previewImage: '/style-previews/neon-cyberpunk.jpg',
  },
  {
    id: 'paper-cutout',
    name: 'Paper Cutout',
    label_zh: '剪纸艺术',
    promptModifier: 'layered paper cutout style sticker, craft art, textured paper, depth shadows, handmade feel',
    previewColor: 'bg-orange-300',
    previewImage: '/style-previews/paper-cutout.jpg',
  },
  {
    id: 'graffiti',
    name: 'Graffiti',
    label_zh: '街头涂鸦',
    promptModifier: 'urban graffiti sticker, spray paint texture, street art, drips, bold wildstyle, vibrant',
    previewColor: 'bg-lime-500',
    previewImage: '/style-previews/graffiti.jpg',
  },
  {
    id: 'holographic',
    name: 'Holographic',
    label_zh: '全息镭射',
    promptModifier: 'holographic sticker, iridescent foil texture, metallic rainbow reflections, shiny, chromatic aberration',
    previewColor: 'bg-cyan-300',
    previewImage: '/style-previews/holographic.jpg',
  },
  {
    id: 'sketch',
    name: 'Pencil Sketch',
    label_zh: '铅笔素描',
    promptModifier: 'pencil sketch sticker, hand-drawn graphite, rough lines, artistic, monochrome or muted colors',
    previewColor: 'bg-stone-400',
    previewImage: '/style-previews/sketch.jpg',
  },
  {
    id: 'anime',
    name: 'Anime',
    label_zh: '日系动漫',
    promptModifier: 'anime manga sticker, cel shaded, vibrant, japanese animation style, expressive, clean lines',
    previewColor: 'bg-rose-400',
    previewImage: '/style-previews/anime.jpg',
  },
  {
    id: 'flat-emoji',
    name: 'Flat Emoji',
    label_zh: '扁平表情',
    promptModifier: 'flat design emoji style, minimal vector, solid colors, UI icon aesthetic, simple shapes',
    previewColor: 'bg-yellow-300',
    previewImage: '/style-previews/flat-emoji.jpg',
  },
  {
    id: 'impressionist',
    name: 'Impressionist',
    label_zh: '印象油画',
    promptModifier: 'oil painting sticker, thick brush strokes, impressionist style, textured canvas, artistic',
    previewColor: 'bg-amber-600',
    previewImage: '/style-previews/impressionist.jpg',
  },
  {
    id: 'stained-glass',
    name: 'Stained Glass',
    label_zh: '彩色玻璃',
    promptModifier: 'stained glass sticker, mosaic pattern, vibrant translucent colors, black lead lines, geometric',
    previewColor: 'bg-emerald-600',
    previewImage: '/style-previews/stained-glass.jpg',
  },
  {
    id: 'psychedelic',
    name: 'Psychedelic',
    label_zh: '迷幻波普',
    promptModifier: 'psychedelic pop art sticker, swirling colors, trippy patterns, surreal, groovy, 60s style',
    previewColor: 'bg-violet-500',
    previewImage: '/style-previews/psychedelic.jpg',
  },
];

export const ASPECT_RATIOS = [
  { value: AspectRatio.SQUARE, label: 'Square (1:1)' },
  { value: AspectRatio.PORTRAIT, label: 'Portrait (3:4)' },
  { value: AspectRatio.LANDSCAPE, label: 'Landscape (4:3)' },
  { value: AspectRatio.WIDE, label: 'Wide (16:9)' },
];

export const RESOLUTIONS = [
  { value: ImageResolution.RES_1K, label: 'Standard (1K)' },
  { value: ImageResolution.RES_2K, label: 'High (2K) - Pro Only' },
  { value: ImageResolution.RES_4K, label: 'Ultra (4K) - Pro Only' },
];

export const AVAILABLE_FONTS = [
  { name: 'Standard', family: 'Fredoka, sans-serif' },
  { name: 'Comic', family: 'Bangers, cursive' },
  { name: 'Script', family: 'Pacifico, cursive' },
  { name: 'Sci-Fi', family: 'Orbitron, sans-serif' },
  { name: 'Horror', family: 'Creepster, cursive' },
  { name: 'Elegant', family: 'Abril Fatface, cursive' },
];

export const BACKGROUND_COLORS = [
  { name: 'White', value: 'white', class: 'bg-white border-slate-200' },
  { name: 'Black', value: 'black', class: 'bg-slate-900 border-slate-700' },
  { name: 'Red', value: 'pastel red', class: 'bg-red-500 border-red-600' },
  { name: 'Blue', value: 'pastel blue', class: 'bg-blue-500 border-blue-600' },
  { name: 'Green', value: 'pastel green', class: 'bg-green-500 border-green-600' },
  { name: 'Yellow', value: 'pastel yellow', class: 'bg-yellow-400 border-yellow-500' },
  { name: 'Pink', value: 'pastel pink', class: 'bg-pink-400 border-pink-500' },
  { name: 'Purple', value: 'pastel purple', class: 'bg-purple-500 border-purple-600' },
];

export const DEFAULT_REQUEST_CONFIG = {
  quantity: 1,
  model: ModelType.NANO_BANANA_2,
  aspectRatio: AspectRatio.SQUARE,
  resolution: ImageResolution.RES_1K,
  useFacialFeatures: true,
};

export const LANGUAGE_OPTIONS = [
  { code: 'en', label: 'English', shortLabel: 'EN' },
  { code: 'zh', label: '中文', shortLabel: '中文' },
  { code: 'es', label: 'Español', shortLabel: 'ES' },
  { code: 'fr', label: 'Français', shortLabel: 'FR' },
  { code: 'de', label: 'Deutsch', shortLabel: 'DE' },
  { code: 'ja', label: '日本語', shortLabel: '日本語' },
  { code: 'ko', label: '한국어', shortLabel: '한국어' },
  { code: 'pt', label: 'Português', shortLabel: 'PT' },
] as const;

export const PRESET_PROMPTS = {
  en: [
    "A cute baby fox",
    "A fleet of yellow submarines",
    "A robot eating pizza",
    "A magical tree house",
    "A cat wearing sunglasses"
  ],
  zh: [
    "一只可爱的小狐狸",
    "黄色潜艇舰队",
    "吃披萨的机器人",
    "神奇的树屋",
    "戴墨镜的猫"
  ],
  es: [
    "Un zorrito adorable",
    "Una flota de submarinos amarillos",
    "Un robot comiendo pizza",
    "Una casa del árbol mágica",
    "Un gato con gafas de sol"
  ],
  fr: [
    "Un adorable bébé renard",
    "Une flotte de sous-marins jaunes",
    "Un robot qui mange une pizza",
    "Une cabane magique dans les arbres",
    "Un chat avec des lunettes de soleil"
  ],
  de: [
    "Ein süßer kleiner Fuchs",
    "Eine Flotte gelber U-Boote",
    "Ein Roboter, der Pizza isst",
    "Ein magisches Baumhaus",
    "Eine Katze mit Sonnenbrille"
  ],
  ja: [
    "かわいい子ぎつね",
    "黄色い潜水艦の艦隊",
    "ピザを食べるロボット",
    "魔法のツリーハウス",
    "サングラスをかけた猫"
  ],
  ko: [
    "귀여운 아기 여우",
    "노란 잠수함 함대",
    "피자를 먹는 로봇",
    "마법의 나무 집",
    "선글라스를 낀 고양이"
  ],
  pt: [
    "Uma raposinha fofa",
    "Uma frota de submarinos amarelos",
    "Um robô comendo pizza",
    "Uma casa na árvore mágica",
    "Um gato usando óculos de sol"
  ]
};

export const TRANSLATIONS = {
  en: {
    title_suffix: "Craft",
    subtitle: "AI Generator",
    powered_by: "Powered by Gemini",
    hero_title_1: "Turn ideas into",
    hero_title_2: "Stickers",
    hero_desc: "Create unique, cartoon-style stickers in seconds using advanced AI. Just describe it, style it, and stick it!",
    
    prompt_label: "What do you want to create?",
    prompt_placeholder: "Enter one prompt per line to generate a batch...\nE.g.,\nA happy little fox\nA fleet of submarines",
    prompt_presets: "Try these:",
    
    style_label: "Choose a Style",
    style_custom_count: "Custom",
    style_custom_remove: "Remove style",
    style_import: "Create Custom Style",
    style_modifier: "Style Modifier",
    style_analyzed: "Analyzed Style Description",
    style_my: "MY",
    
    create_style_title: "Create New Style",
    style_desc_placeholder: "Describe the style (e.g. 'Watercolor, soft pastel colors, dreamy vibe')...",
    upload_reference: "Upload Reference Image (Optional)",
    btn_create_style: "Save Style",
    btn_creating_style: "Analyzing & Saving...",
    style_creation_error: "Please provide a description or an image to create a style.",
    style_image_analyzed: "Image analyzed successfully!",

    config_quantity: "Quantity",
    config_ratio: "Ratio",
    config_model: "Model",
    config_resolution: "Resolution",
    config_layout_mode: "Layout Mode",
    config_single_sticker: "Single Sticker",
    config_three_views: "Three Views (Sheet)",
    config_sticker_collection: "Sticker Collection",
    config_sticker_collection_count: "Stickers in one image",
    config_sticker_collection_hint: "Generate multiple small stickers together on one cohesive sheet.",
    config_sticker_border: "White Sticker Border",
    config_facial_features: "Generate Faces",
    
    text_section_title: "Text",
    background_section_title: "Background",
    text_enable: "Add Text?",
    text_input_placeholder: "Enter text, or leave blank for AI to choose",
    font_style: "FONT STYLE",
    text_border: "Add Text Border",
    bg_color: "Background Color",
    
    btn_generate: "Generate Stickers",
    btn_generating: "Crafting your stickers...",
    
    gallery_title: "Your Gallery",
    gallery_category_all: "All Styles",
    select_all: "Select All",
    deselect_all: "Deselect All",
    download_zip: "Download ZIP",
    selected: "Selected",
    zipping: "Zipping...",
    
    empty_gallery_title: "Ready to create?",
    empty_gallery_desc: "Enter a prompt above and choose a style to generate your first batch of custom stickers!",
    
    error_generic: "Something went wrong while generating stickers. Please try again.",
    
    sticker_details: "Sticker Details",
    created: "Created",
    download_png: "Download PNG",
    
    custom_style_name: "My Style",

    action_delete: "Delete",
    action_regenerate: "Regenerate / Remix",
    action_clear_image: "Clear Image",
    
    prompt_generator_title: "Prompt Generator",
    prompt_generator_placeholder: "Enter a category (e.g. 'Plants', 'Fast Food')",
    prompt_generator_btn: "Generate List",
    prompt_generator_use: "Use These",
    
    upload_image_title: "Upload to Gallery",
    upload_image_desc: "Add your own image to the gallery.",
    upload_image_classification: "Classification / Style",
    upload_image_prompt: "Description / Prompt",
    btn_upload: "Upload",
    btn_uploading: "Uploading...",
    creation_palette: "Creation Palette",
    error_oops: "Oops!",
    use_image_reference: "Use Image Reference",
    pick_existing: "Pick existing",
    type_new: "Type new",
    custom_model_option: "Custom model name...",
    config_model_hint: "Using {provider} image models. Enter a custom name if your proxy exposes different model IDs.",
    style_creation_failed: "Failed to create style. Please try again.",
    zip_failed: "Failed to create zip file.",
    confirm_delete_title: "Delete stickers?",
    confirm_delete_body: "Delete {count} selected stickers? This cannot be undone.",
    action_cancel: "Cancel",
    action_confirm: "Confirm",
    mobile_tab_create: "Create",
    mobile_tab_gallery: "Gallery",
    mobile_tab_nav: "Main navigation",
    section_core: "Core",
    section_reference_layout: "Reference & Layout",
    section_output_settings: "Output Settings",
    section_advanced: "Advanced Options",
    empty_try_preset: "Try a preset prompt",
    gallery_title_prefix: "Sticker",
    gallery_title_accent: "Gallery",
    gallery_description: "Review generated assets, transparency state, and batch export readiness.",
    asset_transparent: "Transparent PNG",
    asset_background_kept: "Background kept",
    asset_uploaded: "Uploaded asset",
    asset_white_border: "White border",
    asset_no_border: "No border",
    asset_collection: "Sticker set",
    asset_text: "Text",
    asset_reference: "Reference image",
    asset_readiness: "Asset readiness",
    asset_transparent_note: "Transparency is created from a controlled solid-background workflow; inspect glow, hair, or soft edges before print use.",
    asset_background_note: "This asset keeps its generated background for posters, cards, or sticker art that needs a scene.",
    asset_uploaded_note: "This was uploaded manually; transparency depends on the original file.",
    asset_api_trust: "API keys stay in browser settings; add a backend proxy and quota protection before public shared deployments.",
    upload_style_placeholder: "e.g. My Custom Style",
    layout_type_title: "Generation type",
    layout_collection_count: "Stickers in this sheet",
    layout_custom_count_hint: "AI may struggle to place too many stickers on one image. Please review the result.",
    layout_item_title: "Mini sticker subjects",
    layout_item_hint: "Type them manually, or generate them from the main prompt.",
    layout_item_placeholder: "Sticker {index} subject",
    layout_generate_items: "Generate subjects",
    layout_generating_items: "Generating...",
    output_transparent_mode: "Transparent PNG workflow",
    output_transparent_hint_black: "Uses a solid black generation background to protect the white border, then removes the background.",
    output_transparent_hint_white: "Uses a solid white generation background, then removes it for icon, sticker-pack, and transparent asset workflows.",
    output_background_mode: "Background kept",
    output_background_hint: "Keeps the selected background color for posters, cards, or scene-style assets.",
  },
  zh: {
    title_suffix: "工坊",
    subtitle: "AI 生成器",
    powered_by: "由 Gemini 驱动",
    hero_title_1: "将创意转化为",
    hero_title_2: "贴纸",
    hero_desc: "利用先进的 AI 技术，瞬间将创意转化为独特的卡通贴纸。只需描述、选择风格，即可生成！",
    
    prompt_label: "你想创作什么？",
    prompt_placeholder: "每行输入一个提示词以进行批量生成...\n例如：\n一只快乐的小狐狸\n一支潜艇舰队",
    prompt_presets: "试试这些：",
    
    style_label: "选择风格",
    style_custom_count: "自定义",
    style_custom_remove: "删除风格",
    style_import: "创建自定义风格",
    style_modifier: "风格描述",
    style_analyzed: "AI分析的风格描述",
    style_my: "我",

    create_style_title: "创建新风格",
    style_desc_placeholder: "描述风格 (例如 '水彩画，柔和的色彩，梦幻氛围')...",
    upload_reference: "上传参考图片 (可选)",
    btn_create_style: "保存风格",
    btn_creating_style: "正在分析并保存...",
    style_creation_error: "请提供风格描述或参考图片。",
    style_image_analyzed: "图片分析成功！",
    
    config_quantity: "数量 (每种)",
    config_ratio: "比例",
    config_model: "模型",
    config_resolution: "分辨率",
    config_layout_mode: "布局模式",
    config_single_sticker: "普通贴纸",
    config_three_views: "生成三视图 (设定图)",
    config_sticker_collection: "生成贴纸集合",
    config_sticker_collection_count: "每张小贴纸数量",
    config_sticker_collection_hint: "在一张图里生成多个统一风格的小贴纸。",
    config_sticker_border: "生成贴纸白边 (描边)",
    config_facial_features: "生成面部/表情",
    
    text_section_title: "文字",
    background_section_title: "背景",
    text_enable: "添加文字？",
    text_input_placeholder: "输入文字，留空则由 AI 自己决定",
    font_style: "字体风格",
    text_border: "添加文字描边",
    bg_color: "背景颜色",
    
    btn_generate: "生成贴纸",
    btn_generating: "正在制作贴纸...",
    
    gallery_title: "你的图库",
    gallery_category_all: "全部风格",
    select_all: "全选",
    deselect_all: "取消全选",
    download_zip: "下载 ZIP",
    selected: "已选择",
    zipping: "正在压缩...",
    
    empty_gallery_title: "准备好创作了吗？",
    empty_gallery_desc: "在上方输入提示词并选择一种风格，开始生成你的第一批专属贴纸！",
    
    error_generic: "生成贴纸时出现问题，请重试。",
    
    sticker_details: "贴纸详情",
    created: "创建时间",
    download_png: "下载 PNG",
    
    custom_style_name: "我的风格",

    action_delete: "删除",
    action_regenerate: "重绘 / 变体",
    action_clear_image: "清除图片",
    
    prompt_generator_title: "提示词生成器",
    prompt_generator_placeholder: "输入类别 (例如 '植物', '快餐')",
    prompt_generator_btn: "生成列表",
    prompt_generator_use: "使用这些",
    
    upload_image_title: "上传到图库",
    upload_image_desc: "将你自己的图片添加到图库中。",
    upload_image_classification: "分类 / 风格",
    upload_image_prompt: "描述 / 提示词",
    btn_upload: "上传",
    btn_uploading: "正在上传...",
    creation_palette: "创作面板",
    error_oops: "出错了",
    use_image_reference: "使用参考图",
    pick_existing: "选择已有",
    type_new: "输入新分类",
    custom_model_option: "自定义模型名称...",
    config_model_hint: "当前使用 {provider} 图片模型；如果中转站改了模型名，可在这里手动输入。",
    style_creation_failed: "创建风格失败，请重试。",
    zip_failed: "创建 ZIP 文件失败。",
    confirm_delete_title: "删除贴纸？",
    confirm_delete_body: "确定删除选中的 {count} 张贴纸吗？此操作无法撤销。",
    action_cancel: "取消",
    action_confirm: "确认",
    mobile_tab_create: "创作",
    mobile_tab_gallery: "图库",
    mobile_tab_nav: "主导航",
    section_core: "核心设置",
    section_reference_layout: "参考与布局",
    section_output_settings: "输出设置",
    section_advanced: "高级选项",
    empty_try_preset: "试试预设提示词",
    gallery_title_prefix: "贴纸",
    gallery_title_accent: "图库",
    gallery_description: "快快准备，获得你的贴纸",
    asset_transparent: "透明 PNG",
    asset_background_kept: "保留背景",
    asset_uploaded: "上传素材",
    asset_white_border: "白边",
    asset_no_border: "无白边",
    asset_collection: "贴纸集合",
    asset_text: "含文字",
    asset_reference: "参考图",
    asset_readiness: "素材状态",
    asset_transparent_note: "透明结果由纯色背景生成后处理得到；复杂发光、头发或半透明边缘仍建议复查。",
    asset_background_note: "该素材保留了生成背景，适合海报、卡片或需要背景的贴纸图。",
    asset_uploaded_note: "这是手动上传到图库的素材，透明状态取决于原始文件。",
    asset_api_trust: "API Key 保存在浏览器本地配置中；公开部署前请加后端代理和额度保护。",
    upload_style_placeholder: "例如：我的自定义风格",
    layout_type_title: "生成类型",
    layout_collection_count: "子贴纸数量",
    layout_custom_count_hint: "AI 可能无法在一张图上生成过多的贴纸，请注意。",
    layout_item_title: "每张子贴纸内容",
    layout_item_hint: "可手动输入，也可以根据上方提示词一键生成。",
    layout_item_placeholder: "第 {index} 张贴纸内容",
    layout_generate_items: "AI 生成子内容",
    layout_generating_items: "生成中...",
    output_transparent_mode: "透明 PNG 工作流",
    output_transparent_hint_black: "会先生成黑色纯色背景以保护白边，再尝试移除背景。",
    output_transparent_hint_white: "会先生成白色纯色背景，再尝试移除背景。适合图标、贴纸包和透明素材。",
    output_background_mode: "保留背景",
    output_background_hint: "会保留你选择的背景色，适合海报、卡片或场景图。",
  },
  es: {
    title_suffix: "Craft",
    subtitle: "Generador IA",
    powered_by: "Impulsado por Gemini",
    hero_title_1: "Convierte ideas en",
    hero_title_2: "Stickers",
    hero_desc: "Crea stickers únicos de estilo caricatura en segundos con IA avanzada.",
    prompt_label: "¿Qué quieres crear?",
    prompt_placeholder: "Escribe un prompt por línea para generar en lote...\nEj.:\nUn zorrito feliz\nUna flota de submarinos",
    prompt_presets: "Prueba estos:",
    style_label: "Elige un estilo",
    style_custom_count: "Personalizado",
    style_custom_remove: "Eliminar estilo",
    style_import: "Crear estilo personalizado",
    style_modifier: "Modificador de estilo",
    style_analyzed: "Descripción de estilo analizada",
    style_my: "MI",
    create_style_title: "Crear nuevo estilo",
    style_desc_placeholder: "Describe el estilo (ej. 'acuarela, colores pastel suaves, ambiente soñador')...",
    upload_reference: "Subir imagen de referencia (opcional)",
    btn_create_style: "Guardar estilo",
    btn_creating_style: "Analizando y guardando...",
    style_creation_error: "Proporciona una descripción o una imagen para crear un estilo.",
    style_image_analyzed: "Imagen analizada correctamente.",
    config_quantity: "Cantidad",
    config_ratio: "Relación",
    config_model: "Modelo",
    config_resolution: "Resolución",
    config_layout_mode: "Modo de diseño",
    config_single_sticker: "Sticker único",
    config_three_views: "Tres vistas",
    config_sticker_collection: "Colección de stickers",
    config_sticker_collection_count: "Stickers por imagen",
    config_sticker_collection_hint: "Genera varios stickers pequeños juntos en una lámina coherente.",
    config_sticker_border: "Borde blanco",
    config_facial_features: "Generar caras",
    text_section_title: "Texto",
    background_section_title: "Fondo",
    text_enable: "¿Agregar texto?",
    text_input_placeholder: "Escribe texto o deja vacío para que la IA elija",
    font_style: "Estilo de fuente",
    text_border: "Borde de texto",
    bg_color: "Color de fondo",
    btn_generate: "Generar stickers",
    btn_generating: "Creando stickers...",
    gallery_title: "Tu galería",
    gallery_category_all: "Todos los estilos",
    select_all: "Seleccionar todo",
    deselect_all: "Deseleccionar todo",
    download_zip: "Descargar ZIP",
    selected: "Seleccionados",
    zipping: "Comprimiendo...",
    empty_gallery_title: "¿Listo para crear?",
    empty_gallery_desc: "Escribe un prompt y elige un estilo para generar tu primera tanda de stickers.",
    error_generic: "Algo salió mal al generar stickers. Inténtalo de nuevo.",
    sticker_details: "Detalles del sticker",
    created: "Creado",
    download_png: "Descargar PNG",
    custom_style_name: "Mi estilo",
    action_delete: "Eliminar",
    action_regenerate: "Regenerar / Remix",
    action_clear_image: "Borrar imagen",
    prompt_generator_title: "Generador de prompts",
    prompt_generator_placeholder: "Ingresa una categoría (ej. 'Plantas', 'Comida rápida')",
    prompt_generator_btn: "Generar lista",
    prompt_generator_use: "Usar estos",
    upload_image_title: "Subir a galería",
    upload_image_desc: "Agrega tu propia imagen a la galería.",
    upload_image_classification: "Clasificación / Estilo",
    upload_image_prompt: "Descripción / Prompt",
    btn_upload: "Subir",
    btn_uploading: "Subiendo...",
    creation_palette: "Panel de creación",
    error_oops: "¡Ups!",
    use_image_reference: "Usar imagen de referencia",
    pick_existing: "Elegir existente",
    type_new: "Escribir nuevo",
    custom_model_option: "Nombre de modelo personalizado...",
    config_model_hint: "Usando modelos de imagen de {provider}. Ingresa un nombre personalizado si tu proxy usa otros IDs.",
    style_creation_failed: "No se pudo crear el estilo. Inténtalo de nuevo.",
    zip_failed: "No se pudo crear el archivo ZIP.",
    confirm_delete_title: "¿Eliminar stickers?",
    confirm_delete_body: "¿Eliminar {count} stickers seleccionados? Esta acción no se puede deshacer.",
    action_cancel: "Cancelar",
    action_confirm: "Confirmar",
    mobile_tab_create: "Crear",
    mobile_tab_gallery: "Galería",
    mobile_tab_nav: "Navegación principal",
    section_core: "Principal",
    section_reference_layout: "Referencia y diseño",
    section_output_settings: "Configuración de salida",
    section_advanced: "Opciones avanzadas",
    empty_try_preset: "Probar un prompt predefinido",
    gallery_title_prefix: "Galería de",
    gallery_title_accent: "Stickers",
    gallery_description: "Revisa los recursos generados, el estado de transparencia y la exportación por lotes.",
    asset_transparent: "PNG transparente",
    asset_background_kept: "Fondo conservado",
    asset_uploaded: "Recurso subido",
    asset_white_border: "Borde blanco",
    asset_no_border: "Sin borde",
    asset_collection: "Colección",
    asset_text: "Texto",
    asset_reference: "Imagen de referencia",
    asset_readiness: "Estado del recurso",
    asset_transparent_note: "La transparencia se crea con un flujo de fondo sólido; revisa bordes suaves antes de imprimir.",
    asset_background_note: "Este recurso conserva el fondo generado para pósters o escenas.",
    asset_uploaded_note: "Subido manualmente; la transparencia depende del archivo original.",
    asset_api_trust: "Las claves API se guardan en el navegador; añade un proxy backend antes de despliegues públicos.",
    upload_style_placeholder: "ej. Mi estilo personalizado",
    layout_type_title: "Tipo de generación",
    layout_collection_count: "Stickers en esta hoja",
    layout_custom_count_hint: "La IA puede tener dificultades con demasiados stickers en una imagen.",
    layout_item_title: "Contenido de mini stickers",
    layout_item_hint: "Escríbelos manualmente o genera desde el prompt principal.",
    layout_item_placeholder: "Sticker {index}",
    layout_generate_items: "Generar contenidos",
    layout_generating_items: "Generando...",
    output_transparent_mode: "Flujo PNG transparente",
    output_transparent_hint_black: "Usa fondo negro sólido para proteger el borde blanco, luego lo elimina.",
    output_transparent_hint_white: "Usa fondo blanco sólido y luego lo elimina para activos transparentes.",
    output_background_mode: "Fondo conservado",
    output_background_hint: "Conserva el color de fondo seleccionado para pósters o escenas.",
  },
  fr: {
    title_suffix: "Craft",
    subtitle: "Générateur IA",
    powered_by: "Propulsé par Gemini",
    hero_title_1: "Transformez vos idées en",
    hero_title_2: "Stickers",
    hero_desc: "Créez en quelques secondes des stickers uniques de style cartoon avec l'IA.",
    prompt_label: "Que voulez-vous créer ?",
    prompt_placeholder: "Entrez un prompt par ligne pour générer un lot...\nEx. :\nUn petit renard joyeux\nUne flotte de sous-marins",
    prompt_presets: "Essayez ceci :",
    style_label: "Choisir un style",
    style_custom_count: "Personnalisé",
    style_custom_remove: "Supprimer le style",
    style_import: "Créer un style personnalisé",
    style_modifier: "Modificateur de style",
    style_analyzed: "Description de style analysée",
    style_my: "MON",
    create_style_title: "Créer un nouveau style",
    style_desc_placeholder: "Décrivez le style (ex. 'aquarelle, tons pastel, ambiance rêveuse')...",
    upload_reference: "Importer une image de référence (facultatif)",
    btn_create_style: "Enregistrer le style",
    btn_creating_style: "Analyse et enregistrement...",
    style_creation_error: "Ajoutez une description ou une image pour créer un style.",
    style_image_analyzed: "Image analysée avec succès.",
    config_quantity: "Quantité",
    config_ratio: "Format",
    config_model: "Modèle",
    config_resolution: "Résolution",
    config_layout_mode: "Mode de mise en page",
    config_single_sticker: "Sticker unique",
    config_three_views: "Trois vues",
    config_sticker_collection: "Collection de stickers",
    config_sticker_collection_count: "Stickers par image",
    config_sticker_collection_hint: "Génère plusieurs petits stickers ensemble sur une planche cohérente.",
    config_sticker_border: "Bord blanc",
    config_facial_features: "Générer des visages",
    text_section_title: "Texte",
    background_section_title: "Fond",
    text_enable: "Ajouter du texte ?",
    text_input_placeholder: "Entrez du texte ou laissez vide pour laisser l'IA choisir",
    font_style: "Style de police",
    text_border: "Contour du texte",
    bg_color: "Couleur de fond",
    btn_generate: "Générer les stickers",
    btn_generating: "Création des stickers...",
    gallery_title: "Votre galerie",
    gallery_category_all: "Tous les styles",
    select_all: "Tout sélectionner",
    deselect_all: "Tout désélectionner",
    download_zip: "Télécharger ZIP",
    selected: "Sélectionnés",
    zipping: "Compression...",
    empty_gallery_title: "Prêt à créer ?",
    empty_gallery_desc: "Entrez un prompt et choisissez un style pour générer vos premiers stickers.",
    error_generic: "Une erreur est survenue lors de la génération. Réessayez.",
    sticker_details: "Détails du sticker",
    created: "Créé",
    download_png: "Télécharger PNG",
    custom_style_name: "Mon style",
    action_delete: "Supprimer",
    action_regenerate: "Régénérer / Remix",
    action_clear_image: "Effacer l'image",
    prompt_generator_title: "Générateur de prompts",
    prompt_generator_placeholder: "Entrez une catégorie (ex. 'Plantes', 'Fast-food')",
    prompt_generator_btn: "Générer la liste",
    prompt_generator_use: "Utiliser ceci",
    upload_image_title: "Importer dans la galerie",
    upload_image_desc: "Ajoutez votre propre image à la galerie.",
    upload_image_classification: "Classification / Style",
    upload_image_prompt: "Description / Prompt",
    btn_upload: "Importer",
    btn_uploading: "Importation...",
    creation_palette: "Panneau de création",
    error_oops: "Oups !",
    use_image_reference: "Utiliser une image de référence",
    pick_existing: "Choisir existant",
    type_new: "Saisir nouveau",
    custom_model_option: "Nom de modèle personnalisé...",
    config_model_hint: "Modèles image {provider}. Saisissez un nom personnalisé si votre proxy utilise d'autres IDs.",
    style_creation_failed: "Échec de création du style. Réessayez.",
    zip_failed: "Échec de création du fichier ZIP.",
    confirm_delete_title: "Supprimer les stickers ?",
    confirm_delete_body: "Supprimer {count} stickers sélectionnés ? Cette action est irréversible.",
    action_cancel: "Annuler",
    action_confirm: "Confirmer",
    mobile_tab_create: "Créer",
    mobile_tab_gallery: "Galerie",
    mobile_tab_nav: "Navigation principale",
    section_core: "Essentiel",
    section_reference_layout: "Référence et mise en page",
    section_output_settings: "Paramètres de sortie",
    section_advanced: "Options avancées",
    empty_try_preset: "Essayer un prompt prédéfini",
    gallery_title_prefix: "Galerie",
    gallery_title_accent: "Stickers",
    gallery_description: "Consultez les ressources générées, la transparence et l'export par lot.",
    asset_transparent: "PNG transparent",
    asset_background_kept: "Fond conservé",
    asset_uploaded: "Ressource importée",
    asset_white_border: "Bord blanc",
    asset_no_border: "Sans bord",
    asset_collection: "Collection",
    asset_text: "Texte",
    asset_reference: "Image de référence",
    asset_readiness: "État de la ressource",
    asset_transparent_note: "Transparence obtenue via un fond uni ; vérifiez les bords avant impression.",
    asset_background_note: "Cette ressource conserve son fond pour affiches ou scènes.",
    asset_uploaded_note: "Importée manuellement ; transparence selon le fichier source.",
    asset_api_trust: "Les clés API restent dans le navigateur ; ajoutez un proxy backend avant déploiement public.",
    upload_style_placeholder: "ex. Mon style personnalisé",
    layout_type_title: "Type de génération",
    layout_collection_count: "Stickers sur cette feuille",
    layout_custom_count_hint: "L'IA peut avoir du mal avec trop de stickers sur une image.",
    layout_item_title: "Sujets des mini stickers",
    layout_item_hint: "Saisissez-les ou générez-les depuis le prompt principal.",
    layout_item_placeholder: "Sticker {index}",
    layout_generate_items: "Générer les sujets",
    layout_generating_items: "Génération...",
    output_transparent_mode: "Flux PNG transparent",
    output_transparent_hint_black: "Fond noir solide pour protéger le bord blanc, puis suppression.",
    output_transparent_hint_white: "Fond blanc solide puis suppression pour assets transparents.",
    output_background_mode: "Fond conservé",
    output_background_hint: "Conserve la couleur de fond pour affiches ou scènes.",
  },
  de: {
    title_suffix: "Craft",
    subtitle: "KI-Generator",
    powered_by: "Bereitgestellt von Gemini",
    hero_title_1: "Mach Ideen zu",
    hero_title_2: "Stickern",
    hero_desc: "Erstelle in Sekunden einzigartige Sticker im Cartoon-Stil mit KI.",
    prompt_label: "Was möchtest du erstellen?",
    prompt_placeholder: "Gib pro Zeile einen Prompt ein...\nZ. B.:\nEin fröhlicher kleiner Fuchs\nEine Flotte U-Boote",
    prompt_presets: "Probiere das:",
    style_label: "Stil wählen",
    style_custom_count: "Benutzerdefiniert",
    style_custom_remove: "Stil entfernen",
    style_import: "Eigenen Stil erstellen",
    style_modifier: "Stilbeschreibung",
    style_analyzed: "Analysierte Stilbeschreibung",
    style_my: "MEIN",
    create_style_title: "Neuen Stil erstellen",
    style_desc_placeholder: "Beschreibe den Stil (z. B. 'Aquarell, sanfte Pastellfarben, verträumt')...",
    upload_reference: "Referenzbild hochladen (optional)",
    btn_create_style: "Stil speichern",
    btn_creating_style: "Analysiere und speichere...",
    style_creation_error: "Bitte gib eine Beschreibung oder ein Bild an.",
    style_image_analyzed: "Bild erfolgreich analysiert.",
    config_quantity: "Anzahl",
    config_ratio: "Format",
    config_model: "Modell",
    config_resolution: "Auflösung",
    config_layout_mode: "Layoutmodus",
    config_single_sticker: "Einzelsticker",
    config_three_views: "Drei Ansichten",
    config_sticker_collection: "Sticker-Sammlung",
    config_sticker_collection_count: "Sticker pro Bild",
    config_sticker_collection_hint: "Erzeugt mehrere kleine Sticker gemeinsam auf einem stimmigen Bogen.",
    config_sticker_border: "Weißer Rand",
    config_facial_features: "Gesichter erzeugen",
    text_section_title: "Text",
    background_section_title: "Hintergrund",
    text_enable: "Text hinzufügen?",
    text_input_placeholder: "Text eingeben oder leer lassen, damit die KI wählt",
    font_style: "Schriftstil",
    text_border: "Textrand",
    bg_color: "Hintergrundfarbe",
    btn_generate: "Sticker generieren",
    btn_generating: "Sticker werden erstellt...",
    gallery_title: "Deine Galerie",
    gallery_category_all: "Alle Stile",
    select_all: "Alle auswählen",
    deselect_all: "Auswahl aufheben",
    download_zip: "ZIP herunterladen",
    selected: "Ausgewählt",
    zipping: "Komprimiere...",
    empty_gallery_title: "Bereit zum Erstellen?",
    empty_gallery_desc: "Gib einen Prompt ein und wähle einen Stil, um deine ersten Sticker zu generieren.",
    error_generic: "Beim Generieren ist ein Fehler aufgetreten. Bitte erneut versuchen.",
    sticker_details: "Sticker-Details",
    created: "Erstellt",
    download_png: "PNG herunterladen",
    custom_style_name: "Mein Stil",
    action_delete: "Löschen",
    action_regenerate: "Neu generieren / Remix",
    action_clear_image: "Bild entfernen",
    prompt_generator_title: "Prompt-Generator",
    prompt_generator_placeholder: "Kategorie eingeben (z. B. 'Pflanzen', 'Fast Food')",
    prompt_generator_btn: "Liste generieren",
    prompt_generator_use: "Diese verwenden",
    upload_image_title: "In Galerie hochladen",
    upload_image_desc: "Füge dein eigenes Bild zur Galerie hinzu.",
    upload_image_classification: "Klassifizierung / Stil",
    upload_image_prompt: "Beschreibung / Prompt",
    btn_upload: "Hochladen",
    btn_uploading: "Lade hoch...",
    creation_palette: "Erstellungspanel",
    error_oops: "Hoppla!",
    use_image_reference: "Referenzbild verwenden",
    pick_existing: "Vorhandenes wählen",
    type_new: "Neu eingeben",
    custom_model_option: "Benutzerdefinierter Modellname...",
    config_model_hint: "Verwendet {provider}-Bildmodelle. Gib einen benutzerdefinierten Namen ein, falls dein Proxy andere IDs nutzt.",
    style_creation_failed: "Stil konnte nicht erstellt werden. Bitte erneut versuchen.",
    zip_failed: "ZIP-Datei konnte nicht erstellt werden.",
    confirm_delete_title: "Sticker löschen?",
    confirm_delete_body: "{count} ausgewählte Sticker löschen? Dies kann nicht rückgängig gemacht werden.",
    action_cancel: "Abbrechen",
    action_confirm: "Bestätigen",
    mobile_tab_create: "Erstellen",
    mobile_tab_gallery: "Galerie",
    mobile_tab_nav: "Hauptnavigation",
    section_core: "Kern",
    section_reference_layout: "Referenz & Layout",
    section_output_settings: "Ausgabe",
    section_advanced: "Erweitert",
    empty_try_preset: "Preset-Prompt ausprobieren",
    gallery_title_prefix: "Sticker",
    gallery_title_accent: "Galerie",
    gallery_description: "Generierte Assets, Transparenz und Batch-Export prüfen.",
    asset_transparent: "Transparentes PNG",
    asset_background_kept: "Hintergrund behalten",
    asset_uploaded: "Hochgeladenes Asset",
    asset_white_border: "Weißer Rand",
    asset_no_border: "Kein Rand",
    asset_collection: "Sticker-Set",
    asset_text: "Text",
    asset_reference: "Referenzbild",
    asset_readiness: "Asset-Status",
    asset_transparent_note: "Transparenz über einheitlichen Hintergrund; weiche Kanten vor dem Druck prüfen.",
    asset_background_note: "Behält den generierten Hintergrund für Poster oder Szenen.",
    asset_uploaded_note: "Manuell hochgeladen; Transparenz hängt von der Quelldatei ab.",
    asset_api_trust: "API-Schlüssel bleiben im Browser; Backend-Proxy vor öffentlichem Einsatz hinzufügen.",
    upload_style_placeholder: "z. B. Mein Stil",
    layout_type_title: "Generierungstyp",
    layout_collection_count: "Sticker auf diesem Bogen",
    layout_custom_count_hint: "KI hat Schwierigkeiten mit zu vielen Stickern auf einem Bild.",
    layout_item_title: "Mini-Sticker-Inhalte",
    layout_item_hint: "Manuell eingeben oder aus dem Hauptprompt generieren.",
    layout_item_placeholder: "Sticker {index}",
    layout_generate_items: "Inhalte generieren",
    layout_generating_items: "Generiere...",
    output_transparent_mode: "Transparentes PNG",
    output_transparent_hint_black: "Schwarzer Hintergrund schützt den weißen Rand, dann Entfernung.",
    output_transparent_hint_white: "Weißer Hintergrund, dann Entfernung für transparente Assets.",
    output_background_mode: "Hintergrund behalten",
    output_background_hint: "Behält die gewählte Hintergrundfarbe für Poster oder Szenen.",
  },
  ja: {
    title_suffix: "Craft",
    subtitle: "AI ジェネレーター",
    powered_by: "Gemini 搭載",
    hero_title_1: "アイデアを",
    hero_title_2: "ステッカーに",
    hero_desc: "高度な AI で、ユニークなカートゥーン風ステッカーを数秒で作成できます。",
    prompt_label: "何を作りますか？",
    prompt_placeholder: "1行に1つずつプロンプトを入力...\n例:\n楽しい子ぎつね\n潜水艦の艦隊",
    prompt_presets: "試してみる:",
    style_label: "スタイルを選択",
    style_custom_count: "カスタム",
    style_custom_remove: "スタイルを削除",
    style_import: "カスタムスタイルを作成",
    style_modifier: "スタイル修飾",
    style_analyzed: "解析されたスタイル説明",
    style_my: "MY",
    create_style_title: "新しいスタイルを作成",
    style_desc_placeholder: "スタイルを説明 (例: '水彩、柔らかなパステル、夢のような雰囲気')...",
    upload_reference: "参考画像をアップロード (任意)",
    btn_create_style: "スタイルを保存",
    btn_creating_style: "解析して保存中...",
    style_creation_error: "説明または画像を指定してください。",
    style_image_analyzed: "画像の解析が完了しました。",
    config_quantity: "数量",
    config_ratio: "比率",
    config_model: "モデル",
    config_resolution: "解像度",
    config_layout_mode: "レイアウト",
    config_single_sticker: "単体ステッカー",
    config_three_views: "三面図",
    config_sticker_collection: "ステッカーコレクション",
    config_sticker_collection_count: "1枚あたりの数",
    config_sticker_collection_hint: "複数の小さなステッカーを1枚の統一されたシートに生成します。",
    config_sticker_border: "白いステッカー枠",
    config_facial_features: "顔を生成",
    text_section_title: "文字",
    background_section_title: "背景",
    text_enable: "文字を追加？",
    text_input_placeholder: "文字を入力、または空欄でAIに任せる",
    font_style: "フォント",
    text_border: "文字の縁取り",
    bg_color: "背景色",
    btn_generate: "ステッカーを生成",
    btn_generating: "ステッカーを作成中...",
    gallery_title: "ギャラリー",
    gallery_category_all: "すべてのスタイル",
    select_all: "すべて選択",
    deselect_all: "選択解除",
    download_zip: "ZIP をダウンロード",
    selected: "選択中",
    zipping: "圧縮中...",
    empty_gallery_title: "作成を始めますか？",
    empty_gallery_desc: "プロンプトを入力し、スタイルを選んで最初のステッカーを生成しましょう。",
    error_generic: "生成中に問題が発生しました。もう一度お試しください。",
    sticker_details: "ステッカー詳細",
    created: "作成日時",
    download_png: "PNG をダウンロード",
    custom_style_name: "マイスタイル",
    action_delete: "削除",
    action_regenerate: "再生成 / リミックス",
    action_clear_image: "画像をクリア",
    prompt_generator_title: "プロンプト生成",
    prompt_generator_placeholder: "カテゴリを入力 (例: '植物', 'ファストフード')",
    prompt_generator_btn: "リスト生成",
    prompt_generator_use: "これを使う",
    upload_image_title: "ギャラリーに追加",
    upload_image_desc: "自分の画像をギャラリーに追加します。",
    upload_image_classification: "分類 / スタイル",
    upload_image_prompt: "説明 / プロンプト",
    btn_upload: "アップロード",
    btn_uploading: "アップロード中...",
    creation_palette: "作成パネル",
    error_oops: "エラー",
    use_image_reference: "参考画像を使用",
    pick_existing: "既存を選択",
    type_new: "新規入力",
    custom_model_option: "カスタムモデル名...",
    config_model_hint: "{provider} の画像モデルを使用中。プロキシで別 ID の場合は手動入力してください。",
    style_creation_failed: "スタイルの作成に失敗しました。もう一度お試しください。",
    zip_failed: "ZIP ファイルの作成に失敗しました。",
    confirm_delete_title: "ステッカーを削除しますか？",
    confirm_delete_body: "選択した {count} 枚を削除しますか？元に戻せません。",
    action_cancel: "キャンセル",
    action_confirm: "確認",
    mobile_tab_create: "作成",
    mobile_tab_gallery: "ギャラリー",
    mobile_tab_nav: "メインナビ",
    section_core: "基本",
    section_reference_layout: "参考とレイアウト",
    section_output_settings: "出力設定",
    section_advanced: "詳細オプション",
    empty_try_preset: "プリセットを試す",
    gallery_title_prefix: "ステッカー",
    gallery_title_accent: "ギャラリー",
    gallery_description: "生成アセット、透明状態、一括エクスポートを確認。",
    asset_transparent: "透過 PNG",
    asset_background_kept: "背景を保持",
    asset_uploaded: "アップロード素材",
    asset_white_border: "白枠",
    asset_no_border: "枠なし",
    asset_collection: "コレクション",
    asset_text: "文字",
    asset_reference: "参考画像",
    asset_readiness: "素材状態",
    asset_transparent_note: "単色背景ワークフローで透過を作成。印刷前にエッジを確認してください。",
    asset_background_note: "生成背景を保持。ポスターやシーン向け。",
    asset_uploaded_note: "手動アップロード。透過は元ファイルに依存。",
    asset_api_trust: "API キーはブラウザに保存。公開前にバックエンドプロキシを追加。",
    upload_style_placeholder: "例: マイスタイル",
    layout_type_title: "生成タイプ",
    layout_collection_count: "シート内の枚数",
    layout_custom_count_hint: "1枚に多すぎるステッカーは AI が苦手な場合があります。",
    layout_item_title: "ミニステッカーの内容",
    layout_item_hint: "手入力またはメインプロンプトから生成。",
    layout_item_placeholder: "ステッカー {index}",
    layout_generate_items: "内容を生成",
    layout_generating_items: "生成中...",
    output_transparent_mode: "透過 PNG ワークフロー",
    output_transparent_hint_black: "白枠保護のため黒背景で生成後、背景を除去。",
    output_transparent_hint_white: "白背景で生成後、透過素材用に除去。",
    output_background_mode: "背景を保持",
    output_background_hint: "選択した背景色を保持。ポスターやシーン向け。",
  },
  ko: {
    title_suffix: "Craft",
    subtitle: "AI 생성기",
    powered_by: "Gemini 기반",
    hero_title_1: "아이디어를",
    hero_title_2: "스티커로",
    hero_desc: "고급 AI로 독특한 카툰 스타일 스티커를 몇 초 만에 만들어 보세요.",
    prompt_label: "무엇을 만들까요?",
    prompt_placeholder: "한 줄에 하나씩 프롬프트를 입력하세요...\n예:\n행복한 아기 여우\n잠수함 함대",
    prompt_presets: "이것도 좋아요:",
    style_label: "스타일 선택",
    style_custom_count: "사용자 지정",
    style_custom_remove: "스타일 삭제",
    style_import: "사용자 지정 스타일 만들기",
    style_modifier: "스타일 설명",
    style_analyzed: "분석된 스타일 설명",
    style_my: "내",
    create_style_title: "새 스타일 만들기",
    style_desc_placeholder: "스타일을 설명하세요 (예: '수채화, 부드러운 파스텔, 몽환적인 분위기')...",
    upload_reference: "참고 이미지 업로드 (선택)",
    btn_create_style: "스타일 저장",
    btn_creating_style: "분석 및 저장 중...",
    style_creation_error: "스타일을 만들려면 설명 또는 이미지를 제공하세요.",
    style_image_analyzed: "이미지 분석 완료!",
    config_quantity: "수량",
    config_ratio: "비율",
    config_model: "모델",
    config_resolution: "해상도",
    config_layout_mode: "레이아웃 모드",
    config_single_sticker: "단일 스티커",
    config_three_views: "3면도",
    config_sticker_collection: "스티커 컬렉션",
    config_sticker_collection_count: "이미지당 스티커 수",
    config_sticker_collection_hint: "여러 작은 스티커를 하나의 통일된 시트로 생성합니다.",
    config_sticker_border: "흰색 스티커 테두리",
    config_facial_features: "얼굴 생성",
    text_section_title: "텍스트",
    background_section_title: "배경",
    text_enable: "텍스트 추가?",
    text_input_placeholder: "텍스트를 입력하거나 비워 두면 AI가 선택합니다",
    font_style: "글꼴 스타일",
    text_border: "텍스트 테두리",
    bg_color: "배경색",
    btn_generate: "스티커 생성",
    btn_generating: "스티커 제작 중...",
    gallery_title: "내 갤러리",
    gallery_category_all: "모든 스타일",
    select_all: "전체 선택",
    deselect_all: "선택 해제",
    download_zip: "ZIP 다운로드",
    selected: "선택됨",
    zipping: "압축 중...",
    empty_gallery_title: "만들 준비가 됐나요?",
    empty_gallery_desc: "프롬프트를 입력하고 스타일을 선택해 첫 스티커를 생성하세요.",
    error_generic: "스티커 생성 중 문제가 발생했습니다. 다시 시도하세요.",
    sticker_details: "스티커 상세",
    created: "생성일",
    download_png: "PNG 다운로드",
    custom_style_name: "내 스타일",
    action_delete: "삭제",
    action_regenerate: "재생성 / 리믹스",
    action_clear_image: "이미지 지우기",
    prompt_generator_title: "프롬프트 생성기",
    prompt_generator_placeholder: "카테고리 입력 (예: '식물', '패스트푸드')",
    prompt_generator_btn: "목록 생성",
    prompt_generator_use: "사용하기",
    upload_image_title: "갤러리에 업로드",
    upload_image_desc: "내 이미지를 갤러리에 추가합니다.",
    upload_image_classification: "분류 / 스타일",
    upload_image_prompt: "설명 / 프롬프트",
    btn_upload: "업로드",
    btn_uploading: "업로드 중...",
    creation_palette: "만들기 패널",
    error_oops: "오류",
    use_image_reference: "참고 이미지 사용",
    pick_existing: "기존 선택",
    type_new: "새로 입력",
    custom_model_option: "사용자 지정 모델 이름...",
    config_model_hint: "{provider} 이미지 모델 사용 중. 프록시가 다른 ID를 쓰면 직접 입력하세요.",
    style_creation_failed: "스타일 생성에 실패했습니다. 다시 시도하세요.",
    zip_failed: "ZIP 파일 생성에 실패했습니다.",
    confirm_delete_title: "스티커를 삭제할까요?",
    confirm_delete_body: "선택한 {count}개를 삭제합니다. 되돌릴 수 없습니다.",
    action_cancel: "취소",
    action_confirm: "확인",
    mobile_tab_create: "만들기",
    mobile_tab_gallery: "갤러리",
    mobile_tab_nav: "메인 내비게이션",
    section_core: "핵심",
    section_reference_layout: "참고 및 레이아웃",
    section_output_settings: "출력 설정",
    section_advanced: "고급 옵션",
    empty_try_preset: "프리셋 프롬프트 사용",
    gallery_title_prefix: "스티커",
    gallery_title_accent: "갤러리",
    gallery_description: "생성된 에셋, 투명 상태, 일괄 내보내기를 확인하세요.",
    asset_transparent: "투명 PNG",
    asset_background_kept: "배경 유지",
    asset_uploaded: "업로드 에셋",
    asset_white_border: "흰 테두리",
    asset_no_border: "테두리 없음",
    asset_collection: "스티커 세트",
    asset_text: "텍스트",
    asset_reference: "참고 이미지",
    asset_readiness: "에셋 상태",
    asset_transparent_note: "단색 배경 워크플로로 투명 처리. 인쇄 전 가장자리를 확인하세요.",
    asset_background_note: "생성 배경을 유지. 포스터나 장면용.",
    asset_uploaded_note: "수동 업로드. 투명도는 원본 파일에 따름.",
    asset_api_trust: "API 키는 브라우저에 저장. 공개 배포 전 백엔드 프록시 추가.",
    upload_style_placeholder: "예: 내 스타일",
    layout_type_title: "生成 유형",
    layout_collection_count: "시트당 스티커 수",
    layout_custom_count_hint: "한 이미지에 너무 많은 스티커는 AI가 어려워할 수 있습니다.",
    layout_item_title: "미니 스티커 내용",
    layout_item_hint: "직접 입력하거나 메인 프롬프트에서 생성.",
    layout_item_placeholder: "스티커 {index}",
    layout_generate_items: "내용 생성",
    layout_generating_items: "生成 중...",
    output_transparent_mode: "투명 PNG 워크플로",
    output_transparent_hint_black: "흰 테두리 보호를 위해 검은 배경 후 제거.",
    output_transparent_hint_white: "흰 배경 생성 후 투명 에셋용으로 제거.",
    output_background_mode: "배경 유지",
    output_background_hint: "선택한 배경색 유지. 포스터나 장면용.",
  },
  pt: {
    title_suffix: "Craft",
    subtitle: "Gerador de IA",
    powered_by: "Com Gemini",
    hero_title_1: "Transforme ideias em",
    hero_title_2: "Stickers",
    hero_desc: "Crie stickers únicos em estilo cartoon em segundos com IA avançada.",
    prompt_label: "O que você quer criar?",
    prompt_placeholder: "Digite um prompt por linha para gerar em lote...\nEx.:\nUma raposinha feliz\nUma frota de submarinos",
    prompt_presets: "Experimente:",
    style_label: "Escolha um estilo",
    style_custom_count: "Personalizado",
    style_custom_remove: "Remover estilo",
    style_import: "Criar estilo personalizado",
    style_modifier: "Modificador de estilo",
    style_analyzed: "Descrição de estilo analisada",
    style_my: "MEU",
    create_style_title: "Criar novo estilo",
    style_desc_placeholder: "Descreva o estilo (ex. 'aquarela, tons pastel suaves, clima sonhador')...",
    upload_reference: "Enviar imagem de referência (opcional)",
    btn_create_style: "Salvar estilo",
    btn_creating_style: "Analisando e salvando...",
    style_creation_error: "Forneça uma descrição ou imagem para criar um estilo.",
    style_image_analyzed: "Imagem analisada com sucesso.",
    config_quantity: "Quantidade",
    config_ratio: "Proporção",
    config_model: "Modelo",
    config_resolution: "Resolução",
    config_layout_mode: "Modo de layout",
    config_single_sticker: "Sticker único",
    config_three_views: "Três vistas",
    config_sticker_collection: "Coleção de stickers",
    config_sticker_collection_count: "Stickers por imagem",
    config_sticker_collection_hint: "Gera vários stickers pequenos juntos em uma folha coesa.",
    config_sticker_border: "Borda branca",
    config_facial_features: "Gerar rostos",
    text_section_title: "Texto",
    background_section_title: "Fundo",
    text_enable: "Adicionar texto?",
    text_input_placeholder: "Digite o texto ou deixe em branco para a IA escolher",
    font_style: "Estilo da fonte",
    text_border: "Borda do texto",
    bg_color: "Cor de fundo",
    btn_generate: "Gerar stickers",
    btn_generating: "Criando stickers...",
    gallery_title: "Sua galeria",
    gallery_category_all: "Todos os estilos",
    select_all: "Selecionar tudo",
    deselect_all: "Desmarcar tudo",
    download_zip: "Baixar ZIP",
    selected: "Selecionados",
    zipping: "Compactando...",
    empty_gallery_title: "Pronto para criar?",
    empty_gallery_desc: "Digite um prompt e escolha um estilo para gerar seus primeiros stickers.",
    error_generic: "Algo deu errado ao gerar stickers. Tente novamente.",
    sticker_details: "Detalhes do sticker",
    created: "Criado",
    download_png: "Baixar PNG",
    custom_style_name: "Meu estilo",
    action_delete: "Excluir",
    action_regenerate: "Regenerar / Remix",
    action_clear_image: "Limpar imagem",
    prompt_generator_title: "Gerador de prompts",
    prompt_generator_placeholder: "Digite uma categoria (ex. 'Plantas', 'Fast food')",
    prompt_generator_btn: "Gerar lista",
    prompt_generator_use: "Usar estes",
    upload_image_title: "Enviar para galeria",
    upload_image_desc: "Adicione sua própria imagem à galeria.",
    upload_image_classification: "Classificação / Estilo",
    upload_image_prompt: "Descrição / Prompt",
    btn_upload: "Enviar",
    btn_uploading: "Enviando...",
    creation_palette: "Painel de criação",
    error_oops: "Ops!",
    use_image_reference: "Usar imagem de referência",
    pick_existing: "Escolher existente",
    type_new: "Digitar novo",
    custom_model_option: "Nome de modelo personalizado...",
    config_model_hint: "Usando modelos de imagem {provider}. Digite um nome personalizado se seu proxy usar outros IDs.",
    style_creation_failed: "Falha ao criar estilo. Tente novamente.",
    zip_failed: "Falha ao criar arquivo ZIP.",
    confirm_delete_title: "Excluir stickers?",
    confirm_delete_body: "Excluir {count} stickers selecionados? Isso não pode ser desfeito.",
    action_cancel: "Cancelar",
    action_confirm: "Confirmar",
    mobile_tab_create: "Criar",
    mobile_tab_gallery: "Galeria",
    mobile_tab_nav: "Navegação principal",
    section_core: "Principal",
    section_reference_layout: "Referência e layout",
    section_output_settings: "Configurações de saída",
    section_advanced: "Opções avançadas",
    empty_try_preset: "Experimentar prompt predefinido",
    gallery_title_prefix: "Galeria de",
    gallery_title_accent: "Stickers",
    gallery_description: "Revise os recursos gerados, transparência e exportação em lote.",
    asset_transparent: "PNG transparente",
    asset_background_kept: "Fundo mantido",
    asset_uploaded: "Recurso enviado",
    asset_white_border: "Borda branca",
    asset_no_border: "Sem borda",
    asset_collection: "Coleção",
    asset_text: "Texto",
    asset_reference: "Imagem de referência",
    asset_readiness: "Estado do recurso",
    asset_transparent_note: "Transparência via fluxo de fundo sólido; verifique bordas antes de imprimir.",
    asset_background_note: "Mantém o fundo gerado para pôsteres ou cenas.",
    asset_uploaded_note: "Enviado manualmente; transparência depende do arquivo original.",
    asset_api_trust: "Chaves API ficam no navegador; adicione proxy backend antes de deploy público.",
    upload_style_placeholder: "ex. Meu estilo personalizado",
    layout_type_title: "Tipo de geração",
    layout_collection_count: "Stickers nesta folha",
    layout_custom_count_hint: "A IA pode ter dificuldade com muitos stickers em uma imagem.",
    layout_item_title: "Conteúdo dos mini stickers",
    layout_item_hint: "Digite manualmente ou gere a partir do prompt principal.",
    layout_item_placeholder: "Sticker {index}",
    layout_generate_items: "Gerar conteúdos",
    layout_generating_items: "Gerando...",
    output_transparent_mode: "Fluxo PNG transparente",
    output_transparent_hint_black: "Fundo preto sólido protege a borda branca, depois remove.",
    output_transparent_hint_white: "Fundo branco sólido depois remove para assets transparentes.",
    output_background_mode: "Fundo mantido",
    output_background_hint: "Mantém a cor de fundo para pôsteres ou cenas.",
  }
};
